//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudFirst.DB_context
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_tbl
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string DOB { get; set; }
        public string address { get; set; }
    }
}
